implemented feedback link
so-sc/sosc-website pull request #115
Opened 2018-11-17 01:20 UTC by coderhawk999

2018-11-17 16:20 UTC, haxzie-xx requested changes
I have left a few pointers, IWhat do you think about showing the feedback link only for a week after the event date?

2018-11-17 16:20 UTC, haxzie commented on src/components/btn_event_feedback_link.js
> +    <a href={link}
Somehow this doesn't get rendered properly, the rendered button on the page doesn't seem to have the `href` attribute, thus it's not clickable. I think you might wanna investigate this further.

2018-11-17 16:20 UTC, haxzie commented on src/templates/event.js
> + function feedbac_link(){
Can we rename this function to `feedback_link`?

2018-11-17 16:23 UTC, haxzie-xx commented
@coderhawk999 I have added a few changes and submitted a PR to your fork, take those changes and you are good to continue further.

2018-11-17 16:45 UTC, coderhawk999 commented
Okay cool , il start working on the changes :+1:

2018-11-17 17:47 UTC, coderhawk999 commented
@haxzie  i have made the requireed changes..

2018-11-17 17:57 UTC, haxzie-xx approved these changes

2018-11-17 18:05 UTC, haxzie commented
Awesome :+1: Good job! There are a few additional things to be taken care of now. Since we have mentioned the no. of days the feedback link will be available directly as hardcoded value, we gotta change it. It's a good practice to move things like these into a separate configuration file. you can have a look at the `gatsby-config.js file` in the root directory which sports some of the most used strings. We can create something similar to store these configuration options and `import()` the contents wherever it's required.

2018-11-25 13:18 UTC, haxzie commented
@coderhawk999 any updates on this?

2018-11-25 13:39 UTC, coderhawk999 commented
Dint understand how to put the date class to json data . If give an example . Would be great

2018-11-26 15:54 UTC, coderhawk999 commented
@haxzie Code review :clap::clap:

2018-11-27 15:45 UTC, haxzie commented
> Dint understand how to put the date class to json data . If give an example . Would be great
> @haxzie

We just need to create a `config.json` or `config.js` to store the no. of Days the FeedBack link should be visible. It can be an integer and we can request import the values and check it in here.
https://github.com/haxzie/sosc-website/blob/0a4dcf4e692de4d66b72200911e58205ec4935d5/src/templates/event.js#L23

2018-12-02 04:55 UTC, merged