Updated team page
so-sc/sosc-website pull request #293
Opened 2020-09-03 13:58 UTC by dhanushp

2020-09-03 14:03 UTC, coderhawk999 requested changes
Good work.. maybe sort the team page according to the designation , currently its sorted alphabetical order.

2020-09-04 04:40 UTC, nathanielmathew approved these changes
What if we merge it for now, and then try implementing it after we get all the new members to add their profile? What do you think @coderhawk999

2020-09-04 04:41 UTC, coderhawk999 commented
Okay cool merge this PR .

2020-09-04 04:41 UTC, coderhawk999 approved these changes

2020-09-04 07:32 UTC, merged