Create ashwinkp.md
so-sc/sosc-website pull request #299
Opened 2020-09-05 10:36 UTC by aswykp

2020-09-05 12:11 UTC, dhanushp requested changes
Please recheck the template. You have missed the dashes.

2020-09-07 05:58 UTC, aswykp commented on src/contents/members/ashwinkp.md
> +username: aswykp
---

2020-09-07 06:07 UTC, aswykp commented
done

2020-09-07 07:35 UTC, dhanushp approved these changes

2020-09-07 09:28 UTC, merged