team update
so-sc/sosc-website pull request #407
Opened 2023-06-17 06:44 UTC by srajankumar

2023-06-17 08:40 UTC, Deveesh-Shetty requested changes
I have put some reviews regarding the roles just go through that once

2023-06-17 08:40 UTC, Deveesh-Shetty commented on src/contents/members/Akshess.md
Akshay is current senior

2023-06-17 08:40 UTC, Deveesh-Shetty commented on src/contents/members/Ananya.md
Ananya is also current senior

2023-06-17 08:40 UTC, Deveesh-Shetty commented on src/contents/members/anish.md
Anish is current senior

2023-06-17 08:40 UTC, Deveesh-Shetty commented on src/contents/members/gauravraoj.md
Gaurav is also current senior not Alumni

2023-06-17 08:40 UTC, Deveesh-Shetty commented on src/contents/members/pavan.md
Pavan is current senior

2023-06-17 08:40 UTC, Deveesh-Shetty commented on src/contents/members/vinayak.md
Vinayak is current Senior as well

2023-06-17 08:48 UTC, srajankumar commented
> I have put some reviews regarding the roles just go through that once

so, should i put them in Members?

2023-06-17 08:52 UTC, Deveesh-Shetty commented
> > I have put some reviews regarding the roles just go through that once
> 
> so, should i put them in Members?

Asking seniors.....will let u know

2023-06-19 01:03 UTC, Deveesh-Shetty approved these changes
LGTM ✅

2023-06-19 03:16 UTC, Deveesh-Shetty approved these changes

2023-06-19 04:18 UTC, merged