Synergy-Induction_Programme Event Updated
so-sc/sosc-website pull request #417
Opened 2023-07-09 16:05 UTC by TejasNayak42

Make sure to change the Event thumbnail

2023-07-10 04:31 UTC, Deveesh-Shetty requested changes

2023-07-10 04:31 UTC, Deveesh-Shetty commented on src/contents/events/Synergy/cover.png
Change the cover image to synergy poster

2023-07-10 04:31 UTC, Deveesh-Shetty commented on src/contents/events/Synergy/index.md
Try to add the images in grid in between the texts...looks too large rn

2023-07-10 04:31 UTC, Deveesh-Shetty commented on src/contents/events/Synergy/index.md
Let it go in a sequence eg. SOSWC content with Nihara's photo explaining it

2023-07-11 03:53 UTC, Deveesh-Shetty requested changes

2023-07-11 03:53 UTC, dev-shetty commented on src/contents/events/Synergy/President.jpg
Change my photo to other one, which is good please 😂😂😂

2023-07-11 03:53 UTC, Deveesh-Shetty commented on src/contents/events/Synergy/cover.jpg
Crop the poster a little, its getting cut in the final version

2023-07-11 03:53 UTC, Deveesh-Shetty commented on src/contents/events/Synergy/index.md
> +.
Remove this period

2023-07-11 03:53 UTC, Deveesh-Shetty commented on src/contents/events/Synergy/index.md
> +
Just clean the alignment from here...

2023-07-11 15:47 UTC, TejasNayak42 commented
changes updated ;)

2023-07-11 15:50 UTC, TejasNayak42 commented
changes updated;)

2023-07-12 13:59 UTC, Deveesh-Shetty approved these changes

2023-07-12 13:59 UTC, Deveesh-Shetty commented
LGTM ✅

2023-07-12 13:59 UTC, merged